"""
Affiliate Link Utilities
-------------------------
Generate, store, and resolve tracking URLs for product affiliate links.
Supports multiple affiliate networks: Amazon, Impact, ShareASale, CJ, Awin, Direct.
"""

import hashlib
import logging
from datetime import datetime
from typing import Optional
from urllib.parse import urlencode, urljoin, urlparse, urlunparse, parse_qs, urlencode

logger = logging.getLogger(__name__)

# ── Affiliate Network Config ───────────────────────────────────────────────────
AFFILIATE_NETWORKS = {
    "amazon": {
        "tag_param": "tag",
        "base_domain": "amazon.com",
        "tracking_param": "linkCode",
    },
    "impact": {
        "click_url_prefix": "https://impact.com/click/",
    },
    "shareasale": {
        "click_url_prefix": "https://shareasale.com/r.cfm?",
    },
    "cj": {
        "click_url_prefix": "https://www.anrdoezrs.net/click-",
    },
    "awin": {
        "click_url_prefix": "https://www.awin1.com/cread.php?",
    },
    "direct": {},   # Direct merchant — just add EcoCart tracking params
}

# Our EcoCart affiliate tag (set in Amazon Associates, etc.)
ECOCART_AMAZON_TAG = "ecocart-21"
ECOCART_TRACKING_PARAM = "ecocart_ref"


def generate_redirect_code(product_id: str, user_id: Optional[str] = None) -> str:
    """
    Generate a short, unique redirect code for a product (+ optional user).
    The code is deterministic per product_id but includes a user dimension for analytics.

    Args:
        product_id: MongoDB product ObjectId string.
        user_id: Optional user ObjectId string for attribution.

    Returns:
        8-character alphanumeric short code.
    """
    seed = f"{product_id}:{user_id or 'anon'}"
    return hashlib.sha256(seed.encode()).hexdigest()[:8]


def generate_tracking_url(
    base_url: str,
    product_id: str,
    user_id: Optional[str] = None,
    campaign: str = "organic",
    affiliate_network: Optional[str] = None,
) -> str:
    """
    Append EcoCart tracking parameters to any URL.
    Handles existing query strings correctly.

    Args:
        base_url: The original affiliate/product URL.
        product_id: MongoDB product ObjectId.
        user_id: Optional user ObjectId.
        campaign: Campaign identifier (e.g., "analysis", "search", "organic").
        affiliate_network: "amazon" | "impact" | "direct" | etc.

    Returns:
        URL with tracking parameters appended.
    """
    parsed = urlparse(base_url)
    params = parse_qs(parsed.query, keep_blank_values=True)

    # Add EcoCart tracking parameters
    params["ecocart_pid"] = [product_id]
    params["ecocart_campaign"] = [campaign]
    if user_id:
        params["ecocart_uid"] = [user_id]

    # Network-specific tag injection
    network = affiliate_network or "direct"
    if network == "amazon":
        params["tag"] = [ECOCART_AMAZON_TAG]
        params["linkCode"] = ["as2"]

    # Rebuild URL
    new_query = urlencode(params, doseq=True)
    tracked_url = urlunparse((
        parsed.scheme,
        parsed.netloc,
        parsed.path,
        parsed.params,
        new_query,
        parsed.fragment,
    ))
    return tracked_url


def build_redirect_url(tracking_code: str, base_url: str = "http://localhost:8000") -> str:
    """
    Build the EcoCart redirect URL /r/{code} that handles click tracking.

    Args:
        tracking_code: Short code generated by generate_redirect_code.
        base_url: Base URL of the EcoCart API.

    Returns:
        Full redirect URL, e.g., "https://api.ecocart.com/r/abc12345"
    """
    return urljoin(base_url, f"/r/{tracking_code}")


def extract_domain(url: str) -> str:
    """Extract the domain from a URL for display purposes."""
    try:
        return urlparse(url).netloc.lstrip("www.")
    except Exception:
        return url


def create_redirect_document(
    product_id: str,
    original_url: str,
    user_id: Optional[str] = None,
    affiliate_network: Optional[str] = None,
) -> dict:
    """
    Create a redirect document for storage in MongoDB `redirect_links` collection.

    Args:
        product_id: MongoDB product ObjectId.
        original_url: The destination affiliate URL.
        user_id: Optional user ObjectId (for personalized tracking).
        affiliate_network: Network identifier.

    Returns:
        MongoDB document dict.
    """
    code = generate_redirect_code(product_id, user_id)
    tracked_url = generate_tracking_url(
        base_url=original_url,
        product_id=product_id,
        user_id=user_id,
        affiliate_network=affiliate_network,
    )
    return {
        "code": code,
        "product_id": product_id,
        "user_id": user_id,
        "original_url": original_url,
        "tracked_url": tracked_url,
        "affiliate_network": affiliate_network or "direct",
        "click_count": 0,
        "created_at": datetime.utcnow(),
    }
